### PR TITLE
Replace "npm install" with "npm ci".

### LINKED ISSUE #144: npm install and package-lock.json behavior
Investigate if we need to pin a little better in the starterkit package.json due to current npm install behavior: https://github.com/npm/npm/issues/18286

### PR DESCRIPTION
**Pull request by wu-edward**
Fixes #144.

### CODE REVIEW

**Comment by sarahjean** [comment]
@wu-edward Looks like this is only failing because php 5.;6 is still in the travis file, if you take that out too it should pass.

**Comment by sarahjean** [comment]
@aellison @elm45 This looks like a pretty sensible change.

**Comment by wu-edward** [comment]
@sarahjean Thanks Sarah. Updated Travis PHP versions to 7.1 and 7.2.

**Comment by aellison** [comment]
Looks good. Thanks you @wu-edward!

**Pull request merged**
