### PR TITLE
Styleguide hbs to twig

### PR DESCRIPTION
**Pull request by AllieRays**
Removing handlebars for twig templates for gulp generated style guide.

### CODE REVIEW

**Comment by jenter** [comment]
@sarahjean @aellison could you help in this review. 
We might also want to discuss an option to switch between *.hbs & *.twig.

**Comment by jenter** [comment]
@AllieRays this is great, we are reviewing this week. 
Thanks again for your help!!

cc @bhasselbeck

**Comment by skippednote** [comment]
@AllieRays 👏 

I think we should add a flag to the drush command. So when generating a sub-theme one can choose between`hbs` or `twig`. But lets defaults to `twig`.

```drush cog chn --styleguide=twig```

**Comment by bhasselbeck** [comment]
This is awesome, simple, but great!

**Comment by sarahjean** [comment]
@skippednote I'm not sure there's really much value in supporting an alternate hbs version. D8 uses twig, and twig is basically handlebars for PHP. I'm pro merging this as is and we can add consider adding a handlebars version option later if there turns out to be some sort of demand.

**Comment by skippednote** [comment]
@sarahjean Agreed. Let's merge this 💯

**Pull request merged**
