### PR TITLE
Fixing class issue as per #86.

### PR DESCRIPTION
**Pull request by dakkusingh**

### CODE REVIEW

**Comment by vbouchet31** [comment]
I can confirm the patch fixes the issue, thanks @dakkusingh. However, I am wondering how it should be back ported to custom theme based on Cog. I have not found any information in the documentation about updating a subtheme based on Cog. In addition, I am wondering why this hook_preprocess_block() is copied from cog into the subtheme as it is not overriden in the subtheme by default. (it is not only the case for this preprocess but for all).

**Comment by jenter** [comment]
@dakkusingh thanks for the update. I believe something had changed since this utility example was originally added with an earlier version of D8, possibly with the array existing so no needing to append. I am merging now and investigating the comment from @vbouchet31.

**Comment by vbouchet31** [comment]
Thanks @jenter Do you want me to create separate tickets for my question so we don't lost these?

**Comment by jenter** [comment]
@vbouchet31 yes please

**Comment by danepowell** [comment]
This also fixes errors like this in the console related to contextual links:

> Uncaught TypeError: Cannot read property 'top' of undefined

**Pull request merged**
