### PR TITLE
Revert to latest npm instead of yarn

### PR DESCRIPTION
**Pull request by skippednote**

### CODE REVIEW

**Comment by arknoll** [comment]
@grasmash @sarahjean @skippednote is this PR meant to move cog away from yarn? I am integrating Canary with Pipelines right now and the first error I received wis when attempting to run yarn install --force (which is called via npm run install-tools).

I'm trying to determine how far I should debug if yarn is going to get pulled relatively soon.

**Comment by skippednote** [comment]
@arknoll The reason I'm proposing to move back to npm is to reduce another dependency in the stack. `yarn` was absurdly fast than npm versions prior to v5.
However, the latest release of npm (v5) is substantially faster than pervious and creates a `package-lock.json` similar to `yarn.lock`.

>  ...the first error I received wis when attempting to run yarn install --force...
What was the error you faced?

**Comment by arknoll** [comment]
@skippednote The error I'm seeing in pipelines is because yarn isn't installed. So, I'm working on getting it installed.

**Comment by danepowell** [comment]
@arknoll with Travis you can install Yarn like this, but I don't know if it's possible with Pipelines:

```
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
```

I agree that "one less dependency" would be good. The only problem is that Travis currently runs npm v2, so we'd need to get BLT and Cog to upgrade npm on Travis, if that's even possible.

**Comment by danepowell** [comment]
I verified that using BLT's .travis.yml, upgrading NPM to v5 is as easy as running `npm install npm@latest -g`... although I'm not sure if the time it takes to install the new version is made up for by a faster install later :man_shrugging:

**Comment by aellison** [comment]
Yarn is still faster than yarn (see the benchmarks on this blog post: http://blog.scottlogic.com/2017/06/06/does-npm5-deprecate-yarn.html). I'd like to wait a bit and see if how this Yarn / NPM rivalry plays out before switching again.

The Drupal core js team was recommending using yarn for core dev just last month (https://www.drupal.org/node/2815083), so it's not like we're the only ones left using an obscure tool.

**Comment by danepowell** [comment]
I am by no means an expert in this arena... but based on that blog post, it sounds like Yarn's only advantage is a few seconds shaved off of a completely bare `npm install`. In reality, doesn't that happen pretty rarely (like only on Travis builds)? It seems like a small win to justify folks having to install one more global tool (which I've just found may not be possible on Acquia CD Pipelines).

I do agree that we want to avoid flip-flopping repeatedly on this.

**Comment by aellison** [comment]
@danepowell If installing yarn is impossible on pipelines, then I'm fine with switching back to NPM.  I guess it's inevitable that we are going to be regularly switching out javascript packages as project dynamics change.  @jenter @sarahjean your thoughts?

**Comment by jenter** [comment]
@sarahjean & @aellison, 
My preference would be just to stick with Yarn unless NPM really proved to be worth the update.
BUT since pipelines isn't compatible with Yarn, we should go back to NPM.
We just need to make sure to test this first to avoid any issues. 

cc @danepowell @skippednote @arknoll

**Comment by jenter** [comment]
@skippednote any insight into the Travis errors?

**Comment by skippednote** [comment]
@jenter I've updated the PR. The phpcs issues have been resolve now.

**Comment by aweingarten** [comment]
@jenter I agree we should stick with yarn.  Anecdotally I have been told that NPM is still significantly slower than yarn.  

also pipelines is compatible with yarn.  We are using it today!

**Comment by danepowell** [comment]
Apparently Yarn can be installed on Pipelines like so: `npm install --global yarn`

So the decision really comes down to an uncertain speed boost at the cost of forcing developers to install one more dependency, vs flip flopping and making existing users of Cog/Yarn change their workflows. I'm on the fence.

**Comment by arknoll** [comment]
IMO, eliminating the technical debt of using yarn now will increase efficiency in the future. It will mean users that are updating Cog will need to change some workflow, however, having one less dependency and breakage vector will likely pay dividends in the future.

**Comment by skippednote** [comment]
I'd suggest that we move back to npm. 

1. There are already many package managers to deal with and adding another one to node ecosystem is confusing for developer (experienced on a recent project).
2. npm will eventually become as fast or faster than yarn. They (npm inc) can fine tune there module repositories to improve there package managers (npm) performance which yarn can't.
3. Current implementation of npm (v5) is already 50% faster than what we had with npm v4.

**Comment by jenter** [comment]
@skippednote after discussing with the group, I am fine with going back to NPM.

**Comment by sarahjean** [comment]
Merging!

**Pull request merged**
